---
title: "Data Import"
output: github_document
---

This file is for doing ata import.

```{r}
library(tidyverse)
library(readxl)
library(haven) ##for sas
```

Import first dataset.

```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv", skip = 0,
    na = c("", "NA", ".")
  )
litters_df = janitor::clean_names(litters_df)
```

Import second dataset.

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv", skip = 3, na = c("", "NA", "."))
pups_df = janitor::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

## Head and tail
```{r}
head(litters_df, 20)
tail(pups_df, 5)
```

skimming?
```{r}
skimr::skim(pups_df)
```


## Oh excel...

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

Look at the data!

```{r}
mlb_df
```

Import FOTR words

```{r}
fortr_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
fortr_df
```

What about TT

```{r}
tt_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6")
tt_df
```

## Import SAS

Read in the PULSE dataset

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

## What is so bad about `read.csv()`

Import pups with `read.csv()`

```{r}
pups_df_base = 
  read.csv("data/FAS_pups.csv")
pups_df_base
```
Won't show: lazy about variable names, super slow for big dataset.











